my_name=("Kpesa Caleb Iyako")
print (my_name)
Department=("Mathematics")
print (Department)
scare=("boo!")
print (scare)
sub=("maths+english==science")
outcome=("science_art")
print (sub+outcome)
print (12/.5)
Result=(24.0)
print (Result)
print(2+2)
sum=(4)
print(sum)
print (8%3)
print (2*4*4+2)